<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PeopleSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $people = [
            [
                'name' => 'أحمد علي',
                'N_id' => '1234560012345',
                'non_citizen_ref_no' => null,
                'birth_date' => '1990-01-15',
                'country' => 'ليبي',
                'city' => 'طرابلس',
                'street_address' => 'شارع الجرابة',
                'gender' => 'ذكر',
                'marital_status' => 'متزوج',
                'email' => 'ahmed.ali@example.com',
                'phone' => '0911111111',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'فاطمة عمر',
                'N_id' => '1234560012346',
                'non_citizen_ref_no' => null,
                'birth_date' => '1993-03-22',
                'country' => 'ليبي',
                'city' => 'بنغازي',
                'street_address' => 'شارع عشرين',
                'gender' => 'انثي',
                'marital_status' => 'أعزب',
                'email' => 'fatima.omar@example.com',
                'phone' => '0922222222',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'محمد سالم',
                'N_id' => '1234560012347',
                'non_citizen_ref_no' => null,
                'birth_date' => '1988-07-09',
                'country' => 'ليبي',
                'city' => 'مصراتة',
                'street_address' => 'حي العاصمة',
                'gender' => 'ذكر',
                'marital_status' => 'متزوج',
                'email' => 'mohamed.salem@example.com',
                'phone' => '0913333333',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'سارة خليفة',
                'N_id' => '1234560012348',
                'non_citizen_ref_no' => null,
                'birth_date' => '1995-11-05',
                'country' => 'ليبي',
                'city' => 'سبها',
                'street_address' => 'حي الجديد',
                'gender' => 'انثي',
                'marital_status' => 'متزوج',
                'email' => 'sara.khalifa@example.com',
                'phone' => '0924444444',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'مصطفى عيسى',
                'N_id' => '1234560012349',
                'non_citizen_ref_no' => null,
                'birth_date' => '1985-02-18',
                'country' => 'ليبي',
                'city' => 'الزاوية',
                'street_address' => 'شارع القرضابية',
                'gender' => 'ذكر',
                'marital_status' => 'مطلق',
                'email' => 'mostafa.essa@example.com',
                'phone' => '0915555555',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'ريم فرج',
                'N_id' => '1234560012350',
                'non_citizen_ref_no' => null,
                'birth_date' => '1998-06-30',
                'country' => 'ليبي',
                'city' => 'طرابلس',
                'street_address' => 'قرجي',
                'gender' => 'انثي',
                'marital_status' => 'أعزب',
                'email' => 'reem.faraj@example.com',
                'phone' => '0946666666',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'أيمن يوسف',
                'N_id' => '1234560012351',
                'non_citizen_ref_no' => null,
                'birth_date' => '1992-09-14',
                'country' => 'ليبي',
                'city' => 'الخمس',
                'street_address' => 'وسط المدينة',
                'gender' => 'ذكر',
                'marital_status' => 'متزوج',
                'email' => 'ayman.yousef@example.com',
                'phone' => '0917777777',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'نسرين ميلاد',
                'N_id' => '1234560012352',
                'non_citizen_ref_no' => null,
                'birth_date' => '1999-12-01',
                'country' => 'ليبي',
                'city' => 'درنة',
                'street_address' => 'المدينة القديمة',
                'gender' => 'انثي',
                'marital_status' => 'أعزب',
                'email' => 'nesreen.milad@example.com',
                'phone' => '0938888888',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'name' => 'إبراهيم جمعة',
                'N_id' => '1234560012353',
                'non_citizen_ref_no' => null,
                'birth_date' => '1987-04-11',
                'country' => 'ليبي',
                'city' => 'سرت',
                'street_address' => 'الحي السكني 2',
                'gender' => 'ذكر',
                'marital_status' => 'أرمل',
                'email' => 'ibrahim.jumaa@example.com',
                'phone' => '0919999999',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                // مثال أجنبي: بدون رقم وطني وبــ non_citizen_ref_no
                'name' => 'John Smith',
                'N_id' => null,
                'non_citizen_ref_no' => 'RES-XY-2025-001',
                'birth_date' => '1991-08-08',
                'country' => 'United Kingdom',
                'city' => 'Tripoli',
                'street_address' => 'Airport Road',
                'gender' => 'ذكر', // التزم بالقيم المحددة في enum
                'marital_status' => 'متزوج',
                'email' => 'john.smith@example.com',
                'phone' => '0951010101',
                'image' => null,
                'enabled' => true,
                'delete_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        DB::table('people')->insert($people);
    }
}
